### ISSUE TITLE
v0.3 scope

### ISSUE THREAD

**Issue by izqui** [firm-org/firm-protocol#81]
Mainnet will be upgraded directly from v0.1 to v0.3, requiring a full restart of the system. Subgraph cannot handle the upgrade (version tracking is enabled by recent changes) and storage has been modified in a non-backwards compatible way.

# v0.3

## Budget
- [x] uint40 dates (**STORAGE LAYOUT/ABI ENCODING IMPACT**) #76
- [x] Debit payment #79

## Budget modules
- [x] Module base #75
- [x] Llamapay streams #79
   - [x] Optimize Llamapay forwarders #84 
- ~Recurring payments~

## ~Roles~
Descoped, #88
- ~Support more than 256 roles~
- ~Support for dynamic roles (depending on call result instead of explicit grant/revokes)~

## Factory
- [x] Module registry in UpgradeableModuleProxy #80 

## Test environment
- [x] Testnet faucet #77 
- [x] Better state seeding #78
- [x] Forking tests #85 

## Meta (right before release)
- [x] #93 
  - [x] forge fmt
  - [x] forge snapshot

## Deployments
- [x] #91
- [x] Polygon v0.3 #97
- [x] Mainnet v0.3 #99 
- ~Goerli v0.3~

# v0.2
v0.2 was never deployed to mainnet, only goerli #74 
- [x] Relayer and metatxs #67
- [x] Event signature changes #61, #62
- [x] Bulk payments #65
- [x] Forcing modules are upgradeable and constructor initialization #69
- [x] Better versioning tracking #63

# Removed from scope

- Recurring payments #86
- Roles improvements #88
